# Generated by Django 3.2.2 on 2021-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_companies_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Movie',
            field=models.CharField(choices=[('S', 'Sahoo'), ('M', 'me tera hero'), ('L', 'Laal killa')], default='sahoo', max_length=1),
        ),
    ]
